### ISSUE TITLE
tt0490773 causes Undefined offset: 0 in Title.php:967

### ISSUE THREAD

**Issue by vlahde** [tboothman/imdbphp#155]
Full error report:

```local.ERROR: ErrorException: Undefined offset: 0 in E:\Laravel\videospace\vendor\imdbphp\imdbphp\src\Imdb\Title.php:967
Stack trace:
#0 E:\Laravel\videospace\vendor\imdbphp\imdbphp\src\Imdb\Title.php(967): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined offse...', 'E:\\Laravel\\vide...', 967, Array)
#1 E:\Laravel\videospace\app\lib\Imdb.php(70): Imdb\Title->alsoknow()
#2 E:\Laravel\videospace\app\Jobs\ImdbGrab.php(44): App\lib\Imdb->imdbGrab(Object(App\Title), Array, 'overwrite')
#3 [internal function]: App\Jobs\ImdbGrab->handle()
#4 E:\Laravel\videospace\vendor\laravel\framework\src\Illuminate\Container\Container.php(508): call_user_func_array(Array, Array)
#5 E:\Laravel\videospace\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#6 E:\Laravel\videospace\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\ImdbGrab))
#7 E:\Laravel\videospace\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\ImdbGrab))
#8 E:\Laravel\videospace\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#9 E:\Laravel\videospace\vendor\laravel\framework\src\Illuminate\Queue\CallQueuedHandler.php(47): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\ImdbGrab), false)
#10 E:\Laravel\videospace\vendor\laravel\framework\src\Illuminate\Queue\Jobs\Job.php(73): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#11 E:\Laravel\videospace\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(203): Illuminate\Queue\Jobs\Job->fire()
#12 E:\Laravel\videospace\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(153): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions))
#13 E:\Laravel\videospace\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(75): Illuminate\Queue\Worker->runNextJob('database', 'default', Object(Illuminate\Queue\WorkerOptions))
#14 E:\Laravel\videospace\vendor\laravel\framework\src\Illuminate\Queue\Console\WorkCommand.php(100): Illuminate\Queue\Worker->daemon('database', 'default', Object(Illuminate\Queue\WorkerOptions))
#15 E:\Laravel\videospace\vendor\laravel\framework\src\Illuminate\Queue\Console\WorkCommand.php(84): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default')
#16 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#17 E:\Laravel\videospace\vendor\laravel\framework\src\Illuminate\Container\Container.php(508): call_user_func_array(Array, Array)
#18 E:\Laravel\videospace\vendor\laravel\framework\src\Illuminate\Console\Command.php(169): Illuminate\Container\Container->call(Array)
#19 E:\Laravel\videospace\vendor\symfony\console\Command\Command.php(261): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 E:\Laravel\videospace\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 E:\Laravel\videospace\vendor\symfony\console\Application.php(817): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 E:\Laravel\videospace\vendor\symfony\console\Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 E:\Laravel\videospace\vendor\symfony\console\Application.php(116): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 E:\Laravel\videospace\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 E:\Laravel\videospace\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 {main}  ```

**Comment by jreklund** [comment]
Please test the master release. I think I already solved this in 2c181ba47c7600c4de6c074105e539eddc28b83d. I don't have any problem with this title at least.

**Comment by vlahde** [comment]
> Please test the master release

How to do that? I have 6.1.1 already installed

**Comment by jreklund** [comment]
You can download [master.zip](https://github.com/tboothman/imdbphp/archive/master.zip) from here. And then unpack it in your vendor directory.

**Comment by vlahde** [comment]
Master version is working with akas and with no  Undefined offset: 0 in Title.php:967 error

**Comment by duck7000** [comment]
Just as info

This is why i suggested to do more releases to fixed problems.
In general people don't use master versions but release versions.

Certainly i don't expect a release for every fix but more often would be appreciated

**Comment by vlahde** [comment]
No I was in error before. Master release is fixed on Title.php:967 error but akas do not work in Master

**Comment by jreklund** [comment]
@duck7000 We know... The latest release where 4 days ago and released after a major breakage. This problem didn't even get raised, so hard to know if it actually affected people. FYI this is a type of comment that will get people to loose interest of contributing. Please raise a separate Issue if you want to discus it further.
@vlahde On what title did you have to add that line? Works great on all tests and some random titles.

**Comment by jreklund** [comment]
If that's the case master will fix your problem. It will only return an array in case it's not empty. Will make an release later with it applied.

Before the fix Parsing::table() returned an array like this:
array(array()) and there are nothing in alsoknow() that checks for an empty array inside an array.

**Comment by vlahde** [comment]
yeah but master does not contain fix to empty akas problem

**Comment by jreklund** [comment]
It can't fetch something that aren't there:
https://www.imdb.com/title/tt0490773/releaseinfo

**Comment by vlahde** [comment]
I tried the master version on several titles that have akas. Returned empty on all occasions.

**Comment by jreklund** [comment]
Can you give me some examples? Everything I feed it works.

**Comment by vlahde** [comment]
for example this did not return any akas for me yesterday when I had the master release installed:
https://www.imdb.com/title/tt0048667/

**Comment by jreklund** [comment]
Okey, you must have made an mistake when installing it I'm afraid. I have now published v6.1.2 based on master.

**Comment by vlahde** [comment]
okay, It is possible that I may have made a mistake too. I will try out the new release later, Thanks!

**Comment by vlahde** [comment]
yes I am aware that chache should be cleared and I did. However could be that I have forgotten to do it in some cases
